# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Newtons College Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  WORKSPACE_PATH: "${{ github.workspace }}"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Java Maven
      run: |
        java -version
        mvn -version
        echo " $GITHUB_WORKSPACE"
        echo "test"
        echo "${GITHUB_REPOSITORY##*/}"
        
    - name: Build with Maven
      run: mvn clean install
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp.war
        path: ${{ env.WORKSPACE_PATH }}/webapp/target/webapp.war

  Deploy:
    runs-on: self-hosted
    needs: build
    steps:
    
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: webapp.war
          path: ./artifacts
      - name: deploy to prod
        run: |
          echo "display artifacts"
          ls -ltr ./artifacts
          cp -f ./artifacts/webapp.war  /home/tomcat/apache-tomcat-*/webapps
          nohup /home/tomcat/apache-tomcat-*/bin/startup.sh &
          echo "completed"
          

